[tool.poetry]
name = "project roject"
version = "0.1.0"
description = ""
authors = ["Exoniack <55805926+Exoniack@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
